USE HumanResourcesDepartment;

CREATE TABLE PastWork (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_PastWork PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
	Position VARCHAR(255) NOT NULL,
	BeginDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	ID_Employee UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Employee FOREIGN KEY 
	REFERENCES Employee(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);