USE HumanResourcesDepartment;

CREATE TABLE Unit (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Unit PRIMARY KEY,
    [Name] VARCHAR(255) NOT NULL,
);

ALTER TABLE Unit
ADD CONSTRAINT u_UnitName UNIQUE([Name]);