USE HumanResourcesDepartment;

CREATE TABLE WorkContract (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_WorkContract PRIMARY KEY,
	ContractUI VARCHAR(255) NOT NULL,
	ID_Position UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Position FOREIGN KEY 
	REFERENCES Position(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ID_Rate UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Rate FOREIGN KEY 
	REFERENCES Rate(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	BeginDate DATE NOT NULL,
);

ALTER TABLE WorkContract
ADD CONSTRAINT u_EmployeeContractUI UNIQUE(ContractUI);