USE HumanResourcesDepartment;

CREATE TABLE Employee (
    ID UNIQUEIDENTIFIER DEFAULT NEWID()
	CONSTRAINT PK_Employee PRIMARY KEY,
    FirstName VARCHAR(255) NOT NULL,
	SurName VARCHAR(255) NOT NULL,
	SecondName VARCHAR(255) NOT NULL,
	Birthday DATE NOT NULL,
	HomeAddress VARCHAR(255) NOT NULL,
	TelephoneNumber VARCHAR(255) NOT NULL,
	Passport VARCHAR(255) NOT NULL,
	Pensioner BIT NOT NULL,
	ID_WorkContract UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_WorkContract FOREIGN KEY 
	REFERENCES WorkContract(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ID_Unit UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Unit FOREIGN KEY 
	REFERENCES Unit(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
	ID_Gender UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT FK_Gender FOREIGN KEY 
	REFERENCES Gender(ID)
	ON DELETE CASCADE 
	ON UPDATE CASCADE,
);

ALTER TABLE Employee
ADD CONSTRAINT u_EmployeePassport UNIQUE(Passport);