CREATE FUNCTION dbo.fGenderID
(
	@GenderName VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Gender UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Gender WHERE [Name] = @GenderName);
	RETURN @ID_Gender;
END;