CREATE FUNCTION dbo.fUnitID
(
	@UnitName VARCHAR(255)
)
RETURNS UNIQUEIDENTIFIER
AS
BEGIN
	DECLARE @ID_Unit UNIQUEIDENTIFIER = (SELECT TOP 1 ID FROM Unit WHERE [Name] = @UnitName);
	RETURN @ID_Unit;
END;